# baseURL = 'http://0.0.0.0:1313/hugo-book/'
title = 'Maplestory R: Evolution compendium'
# theme = 'hugo-book'

# Theme: Book configuration
# (Optional) Set this to true if you use capital letters in file names
disablePathToLower = true

# (Optional) Set this to true to enable 'Last Modified by' date and git author
#  information on 'doc' type pages.
enableGitInfo = true

# (Optional) Theme is intended for documentation use, therefore it doesn't render taxonomy.
# You can remove related files with config below
disableKinds = ['taxonomy']

# Needed for mermaid/katex shortcodes
[markup]
[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 1

# Multi-lingual mode config
# There are different options to translate files
# See https://gohugo.io/content-management/multilingual/#translation-by-filename
# And https://gohugo.io/content-management/multilingual/#translation-by-content-directory
[languages]
[languages.en]
  languageName = 'English'
  contentDir = 'content.en'
  weight = 1

#[languages.zh]
#  languageName = 'Chinese'
#  contentDir = 'content.zh'
#  weight = 2

[menu]
[[menu.home]]
  name = "Compendium"
  url = "/docs/"
  weight = 1

[[menu.home]]
  name = "Play"
  url = "https://msrsea.rastargames.com/"
  weight = 2

[[menu.home]]
  name = "Maplestory R: Evolution Facebook"
  url = "https://www.facebook.com/MapleStoryREvolution"
  weight = 3

[[menu.home]]
  name = "Github"
  url = "https://github.com/mathewng/maplestoryrevolutioncompendium"
  weight = 4

# [[menu.before]]
# [[menu.after]]
#   name = "Github"
#   url = "https://github.com/alex-shpak/hugo-book/"
#   weight = 10

# [[menu.after]]
#   name = "Hugo Themes"
#   url = "https://themes.gohugo.io/themes/hugo-book/"
#   weight = 20
